image: openjdk:17-jdk-alpine

stages:
  - build
  - release

variables:
  MVN_CMD: "./mvnw"
  MVN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  key: "v1-${CI_COMMIT_REF_SLUG}"
  paths:
    - .m2/
    - target/

build:
  stage: build
  script:
    - $MVN_CMD $MVN_CLI_OPTS verify
  artifacts:
    paths:
      - target/

release:
  stage: release
  when: manual
  variables:
    RELEASE_VERSION: ""
    NEXT_VERSION: ""
  only:
    - main
  before_script:
    - |
      apk add --update git gnupg
      mkdir -p ~/.gnupg
    - |
      git config --global user.email "build@oxyeo.dev"
      git config --global user.name "oxyeo-builds"
      git checkout -b temp
    - |
      echo 'allow-loopback-pinentry' > ~/.gnupg/gpg-agent.conf
      echo RELOADAGENT | gpg-connect-agent
    - echo $GPG_PRIVATE_KEY | base64 -d | gpg2 --batch --import
    - |
      export MAVEN_USER_HOME=/root/.m2
      mkdir -p /root/.m2/
    - cp $MAVEN_SETTINGS_SECURITY /root/.m2/settings-security.xml
  script:
    - |
      $MVN_CMD $MVN_CLI_OPTS -X release:prepare release:perform \
      -DreleaseVersion=$RELEASE_VERSION \
      -DdevelopmentVersion=$NEXT_VERSION
